version: "3"
services:
  app:
    restart: always
    build: ./intern-pocket-imdb-express-boilerplate-master
    ports:
      - "3000:3000"
    volumes:
      - ./intern-pocket-imdb-express-boilerplate-master/src:/app/server/src
    links:
      - db
      - redis
  db:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports: 
      - "6379:6379"
  client:
    container_name: client-react-native
    build:
      context: ./intern-pocket-imdb-react-native-boilerplate-master
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
    volumes:
      - ./intern-pocket-imdb-react-native-boilerplate-master:/app/client
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=10.0.46.140
